### ISSUE TITLE
When installing, does it need access to "All repositories"?

### ISSUE THREAD

**Issue by tonglil** [issc29/probot-prevent-public-repos#2]
Or will `org-settings` do?

<img width="572" alt="image" src="https://user-images.githubusercontent.com/3250776/38329442-a4beee48-3802-11e8-83f1-ed3bc1ddabc7.png">

**Comment by tonglil** [comment]
I gave it permission to all, however the Probot does not seem to be working (no issues created). Is this app still functioning?

**Comment by issc29** [comment]
@tonglil apologies as I wasn't watching the repo, so I never saw these questions.

`All Repositories` should be selected because it needs the ability to change the repos from public to private. 

If the app wasnt creating issues, see the [Get Started](https://help.github.com/articles/repository-permission-levels-for-an-organization/#changing-the-visibility-of-repositories) section of the Readme and ensure that this was done:
- [Required] Ensure that the [Repository visibility change](https://help.github.com/articles/repository-permission-levels-for-an-organization/#changing-the-visibility-of-repositories) setting in **Member Privileges** is _checked_ to allow the App to control Repository visibility changes.

Let me know if you any additional questions!
